### ISSUE TITLE
Main Menu Framework/Active Customer Selection

### ISSUE THREAD

**Issue by waamber** [nss-bladeRunners/bangazon-cli#13]

**Comment by waamber** [comment]
Include 'Return to Main Menu'

**Comment by waamber** [comment]
seller && buyer sub menu

**Comment by gib-bowden** [comment]
-View and Actions to get to Add a Customer
-View and Actions to get to Select an active customer

**Comment by gib-bowden** [comment]
As a user opening the application, I want to be presented with the options to add a user or select a user to be active so that I can execute buyer or seller actions in the application.

**Comment by gib-bowden** [comment]
Selecting Add Customer will direct to the add user view - which will be handed by another ticket

**Comment by gib-bowden** [comment]
Selecting Select a Customer will direct the user to a list of all customers in the system where they can select a the user who will be active. Once the user makes a selection, the user will be directed to the customer submenu (Buy/Sell) which will be handled by another item
