### ISSUE TITLE
User should be able to add a product for a customer

### ISSUE THREAD

**Issue by copypastedeveloper** [nss-bladeRunners/bangazon-cli#4]
**Given** a customer has been made active in the program
**When** the user selects the option to add a product
**Then** the user should be prompted to enter in all appropriate information for a product
**And** when complete, the product should be added for the active customer

**Comment by gib-bowden** [comment]
Product table Properties:
ProductId
Name
CustomerId (FK)
Unit Price
Quantity

Product class

Product view

**Comment by lady-ace** [comment]
Temporarily blocked until tickets 2 and 15 are complete.

**Comment by gib-bowden** [comment]
@lady-ace  hey - you should be able to work around these blockers, i was thinking about how i was going to handle these myself. For ticket #2 you can just hardcode the customerId until that's available; for #15 don't worry about the step to get to the add product page, just develop and test the page in isolation from the eventual workflow
